// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlcYzlH5Tch9IGWaaahribvUO32Ndnxhc',
    appId: '1:290160000181:web:1bdc8328a87f56e8a5d2fc',
    messagingSenderId: '290160000181',
    projectId: 'gestion-ticket-cb81b',
    authDomain: 'gestion-ticket-cb81b.firebaseapp.com',
    storageBucket: 'gestion-ticket-cb81b.appspot.com',
    measurementId: 'G-YPL03RLLX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGopzofexdtCreHmB1afxI6joCvLrRqw',
    appId: '1:290160000181:android:b8c133f286b2eb93a5d2fc',
    messagingSenderId: '290160000181',
    projectId: 'gestion-ticket-cb81b',
    storageBucket: 'gestion-ticket-cb81b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8j7q9cc8CsiEbDB74BbwAoG6pN-zOcQo',
    appId: '1:290160000181:ios:a52b8ea371c1fec4a5d2fc',
    messagingSenderId: '290160000181',
    projectId: 'gestion-ticket-cb81b',
    storageBucket: 'gestion-ticket-cb81b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8j7q9cc8CsiEbDB74BbwAoG6pN-zOcQo',
    appId: '1:290160000181:ios:a52b8ea371c1fec4a5d2fc',
    messagingSenderId: '290160000181',
    projectId: 'gestion-ticket-cb81b',
    storageBucket: 'gestion-ticket-cb81b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlcYzlH5Tch9IGWaaahribvUO32Ndnxhc',
    appId: '1:290160000181:web:e5d54d9f779d78e2a5d2fc',
    messagingSenderId: '290160000181',
    projectId: 'gestion-ticket-cb81b',
    authDomain: 'gestion-ticket-cb81b.firebaseapp.com',
    storageBucket: 'gestion-ticket-cb81b.appspot.com',
    measurementId: 'G-L9XX4FQ6G4',
  );
}
